### ISSUE TITLE
Support for SN themes

### ISSUE THREAD

**Issue by selmaohneh** [corvec/sn-kanban-editor#1]
It would be nice if the editor could have colors according to the currently selected theme in SN. A static blue background can be a pain in the eye for some themes. 

Nice work so far! :-)

**Comment by corvec** [comment]
Thanks, I'm glad you like this!

I had to look into how both `react-trello` and Standard Notes handle theming and they're not directly compatible, unfortunately, but Theo Chu pointed me in the right direction. It looks like the solution will basically involve me doing the following for each relevant theme class:

```javascript
const backgroundColor = window.getComputedStyle(document.documentElement).getPropertyValue('--sn-stylekit-background-color').replace(/\s+/g, '');
const color = window.getComputedStyle(document.documentElement).getPropertyValue('--sn-stylekit-foreground-color').replace(/\s+/g, '');
const cardStyles = { backgroundColor, color };
```

I should have time this evening to test out this approach.

**Comment by corvec** [comment]
I've finished adding theme support. It ended up being a bit simpler than I originally thought, thankfully. It should update automatically with the current version for you.

If you run into issues with unreadable text or anything similar, please raise another issue (possibly with a link to the theme in question). I've only tested with the official themes on desktop and mobile. Other than a couple themes where card borders aren't clear, it looks good to me, but it's totally possible that it doesn't look right in some custom themes or in some menu that I didn't test.
